name: CI/CD

on:
  workflow_dispatch:

jobs:
  check-java-v-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Java version
        run: java -version

  check-mvn-v-job:
    needs: check-java-v-job  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: show mvn version
        run: mvn -v

  build:
    needs: [check-java-v-job, check-mvn-v-job]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: building retro-hotel-project
        run : mvn clean package spring-boot:repackage

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: retro-hotel-jar
          path: target/*.jar
