name: Check Java Version

on:
  workflow_dispatch:

jobs:
  check-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Java version
        run: java -version
